# Kubernetes deployment configuration
# Requirement 1.1, 1.3: Kubernetes deployment with health checks

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-platform
  labels:
    app: agent-platform
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agent-platform
  template:
    metadata:
      labels:
        app: agent-platform
        version: v1
    spec:
      containers:
      - name: agent-platform
        image: agent-platform:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: agent-platform-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: agent-platform-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: agent-platform-secrets
              key: jwt-secret
        - name: RUST_LOG
          value: "info"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: agent-platform
  labels:
    app: agent-platform
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: agent-platform

---
apiVersion: v1
kind: Secret
metadata:
  name: agent-platform-secrets
type: Opaque
stringData:
  database-url: "mysql://agent_user:agent_password@mysql:3306/agent_platform"
  redis-url: "redis://redis:6379"
  jwt-secret: "your-secret-key-change-in-production"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-platform-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agent-platform
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
